#pragma once

#define mic_vc_stage_index		(4)
#define music_vc_stage_index		(5)
#define mic_vu_stage_index		(7)
#define denoise_enable_stage_index		(11)
#define reverb_placeholder_stage_index		(13)
#define reverb_enable_stage_index		(14)
#define duck0_enable_stage_index		(20)
#define duck1_enable_stage_index		(21)
#define game_loopback_switch_ch0_stage_index		(25)
#define game_loopback_switch_ch1_stage_index		(26)
#define monitor_vc_stage_index		(27)
#define output_vc_stage_index		(28)
#define out_vu_stage_index		(30)
